// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3ecUfNNgzkwcxK24r-2nBSabtQZbhHsI',
    appId: '1:966423884670:web:2c3e3488588c250405f92f',
    messagingSenderId: '966423884670',
    projectId: 'bayad-system-d4c45',
    authDomain: 'bayad-system-d4c45.firebaseapp.com',
    storageBucket: 'bayad-system-d4c45.appspot.com',
    measurementId: 'G-Y8WE9CFP3S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYHrqkaKacUIpt3hl8RFbak0tkII0Mw5c',
    appId: '1:966423884670:android:fc814560a804538c05f92f',
    messagingSenderId: '966423884670',
    projectId: 'bayad-system-d4c45',
    storageBucket: 'bayad-system-d4c45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0ufGUUyp4HjlVfI6ZMZZf_eCLc7x3xzE',
    appId: '1:966423884670:ios:e6ebf30c3b015beb05f92f',
    messagingSenderId: '966423884670',
    projectId: 'bayad-system-d4c45',
    storageBucket: 'bayad-system-d4c45.appspot.com',
    androidClientId: '966423884670-oib2206sf5jr60dd6jva71pjaraqfasl.apps.googleusercontent.com',
    iosClientId: '966423884670-ossk10khnilmmmh4dos3cibco1ku7t54.apps.googleusercontent.com',
    iosBundleId: 'com.example.bayadSystem',
  );

}